# Generated by Django 6.0.6 on 2026-07-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True, help_text="Укажите id_chat в ТГ", max_length=50, null=True, verbose_name="id_chat_tg"
            ),
        ),
    ]
