# Generated by Django 6.0.6 on 2026-07-02 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите кратко и привлекательно цель привычки",
                        max_length=100,
                        verbose_name="Цель привычки",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место выполнения привычки", max_length=100, verbose_name="Место"
                    ),
                ),
                (
                    "lead_time",
                    models.DateTimeField(
                        help_text="Укажите дату и время выполнения привычки", verbose_name="Дата и время выполнения"
                    ),
                ),
                ("action", models.CharField(help_text="Укажите действие", max_length=100, verbose_name="Действие")),
                (
                    "nice_habit",
                    models.BooleanField(default=False, null=True, verbose_name="Признак приятной привычки"),
                ),
                (
                    "time_to_execute",
                    models.DurationField(help_text="Укажите время выполнения", verbose_name="Время выполнения"),
                ),
                (
                    "frequency_of_execution",
                    models.CharField(
                        choices=[("daily", "Ежедневно"), ("weekly", "Раз в неделю")],
                        default="daily",
                        help_text="Укажите периодичность выполнения привычки: Ежедневно/Раз в неделю",
                        max_length=20,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        max_length=100,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                ("public", models.BooleanField(default=False, null=True, verbose_name="Признак публичности")),
                (
                    "connected_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выбирите связную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["name"],
            },
        ),
    ]
