# Generated by Django 6.0.6 on 2026-07-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency_of_execution",
            field=models.CharField(
                choices=[("Ежедневно", "Ежедневно"), ("Раз в неделю", "Раз в неделю")],
                default="Ежедневно",
                help_text="Укажите периодичность выполнения привычки: Ежедневно/Раз в неделю",
                max_length=20,
                verbose_name="Периодичность",
            ),
        ),
    ]
